USE WAREHOUSE COMPUTE_WH;
USE DATABASE REDBULL_DATA;
USE SCHEMA GOLD;

USE ROLE RB_USA_ANALYST;
SELECT CURRENT_ROLE() AS active_role, ARRAY_AGG(DISTINCT market) AS visible_markets
FROM REDBULL_DATA.GOLD.DIM_OUTLET;

USE ROLE RB_GBR_ANALYST;
SELECT CURRENT_ROLE() AS active_role, ARRAY_AGG(DISTINCT market) AS visible_markets
FROM REDBULL_DATA.GOLD.DIM_OUTLET;

USE ROLE RB_DEU_ANALYST;
SELECT CURRENT_ROLE() AS active_role, ARRAY_AGG(DISTINCT market) AS visible_markets
FROM REDBULL_DATA.GOLD.DIM_OUTLET;

USE ROLE RB_HQ_ANALYST;
SELECT CURRENT_ROLE() AS active_role, ARRAY_AGG(DISTINCT market) AS visible_markets
FROM REDBULL_DATA.GOLD.DIM_OUTLET;

USE ROLE RB_HQ_ANALYST;
SELECT market, COUNT(*) AS listing_count
FROM REDBULL_DATA.GOLD.FCT_OUTLET_PRODUCT_LISTING
GROUP BY market
ORDER BY market;
