/* CREATE RAW FILE FORMAT */
CREATE OR REPLACE FILE FORMAT REDBULL_DATA.BRONZE.RAW_FORMAT
    TYPE = 'CSV'
    FIELD_DELIMITER = NONE
    RECORD_DELIMITER = '\n'
    SKIP_HEADER = 1
    TRIM_SPACE = TRUE
    SKIP_BYTE_ORDER_MARK = TRUE
    ENCODING = 'UTF8'
    NULL_IF = ('NULL', 'null', '');

/* CREATE QUOTE-AWARE TSV FILE FORMAT FOR PARSED BRONZE TABLES */
CREATE OR REPLACE FILE FORMAT REDBULL_DATA.BRONZE.TSV_FORMAT
    TYPE = 'CSV'
    FIELD_DELIMITER = '\t'
    RECORD_DELIMITER = '\n'
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    SKIP_HEADER = 1
    TRIM_SPACE = TRUE
    SKIP_BYTE_ORDER_MARK = TRUE
    ENCODING = 'UTF8'
    EMPTY_FIELD_AS_NULL = TRUE
    NULL_IF = ('NULL', 'null', '');

/* CREATE RAW TABLES */
CREATE OR REPLACE TABLE REDBULL_DATA.BRONZE.MATCHING_RAW (
    MARKET STRING,
    SOURCE_FILE STRING,
    FILE_ROW_NUMBER INT,
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    RAW_DATA STRING
);

CREATE OR REPLACE TABLE REDBULL_DATA.BRONZE.OUTLET_RAW (
    MARKET STRING,
    SOURCE_FILE STRING,
    FILE_ROW_NUMBER INT,
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    RAW_DATA STRING 
);

CREATE OR REPLACE TABLE REDBULL_DATA.BRONZE.PORTFOLIO_RAW (
    MARKET STRING,
    SOURCE_FILE STRING,
    FILE_ROW_NUMBER INT,
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    RAW_DATA STRING 
);

/* CREATE PARSED BRONZE TABLES */
CREATE OR REPLACE TABLE REDBULL_DATA.BRONZE.MATCHING_PARSED (
    MARKET STRING,
    SOURCE_FILE STRING,
    FILE_ROW_NUMBER INT,
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    ID_OUTLET STRING,
    ID_PLATFORM STRING,
    PLATFORM_NAME STRING,
    ID_EXT_LINK STRING,
    PLACE_ID STRING,
    SIMILARITY_SCORE_NAME STRING,
    SIMILARITY_SCORE_ADDRESS STRING,
    MERGED_CHAIN_NAME STRING,
    IS_CHAIN STRING,
    NUM_RESTAURANTS STRING,
    SERVES_DRINKS STRING,
    SERVES_RED_BULL STRING,
    SUGAR_FREE_AVAILABLE STRING,
    ORGANICS_AVAILABLE STRING,
    EDITIONS_AVAILABLE STRING,
    ED STRING,
    ED_COMP STRING,
    SD_COKE STRING,
    SD STRING,
    LEADING_ID_EXT_LINK STRING,
    CREATED_AT STRING
);

CREATE OR REPLACE TABLE REDBULL_DATA.BRONZE.OUTLET_PARSED (
    MARKET STRING,
    SOURCE_FILE STRING,
    FILE_ROW_NUMBER INT,
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    ID_EXT_LINK STRING,
    ID_OUTLET STRING,
    ID_PLATFORM STRING,
    PLATFORM_NAME STRING,
    LINK STRING,
    NAME STRING,
    ADDRESS_BULK STRING,
    BUSINESS STRING,
    BUSINESS_URL STRING,
    DELIVERY STRING,
    CATEGORY STRING,
    DESCRIPTION STRING,
    TELEPHONE STRING,
    LATITUDE STRING,
    LONGITUDE STRING,
    NUM_RATINGS STRING,
    AVERAGE_RATING STRING,
    AVERAGE_COST STRING,
    CITY STRING,
    ICON_URL STRING,
    LOCAL_ICON_NAME STRING,
    MIN_ORDER_AMOUNT STRING,
    BANNER_AVAILABLE STRING,
    BANNER_IMG_LINK STRING,
    BANNER_IMG_HASH STRING,
    MARKET_FIELD STRING,
    STREET_ADDRESS STRING,
    POSTAL_CODE STRING,
    ADDRESS_LOCALITY STRING,
    ADDRESS_COUNTRY STRING,
    TELEPHONE_PLATFORM STRING,
    CUISINE STRING,
    WEBSITE STRING,
    GHOST_KITCHEN STRING,
    LOCAL_CURRENCY STRING,
    CREATED_AT STRING,
    SEGMENT_TYPE STRING
);

CREATE OR REPLACE TABLE REDBULL_DATA.BRONZE.PORTFOLIO_PARSED (
    MARKET STRING,
    SOURCE_FILE STRING,
    FILE_ROW_NUMBER INT,
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    ID_BEVERAGE STRING,
    ID_EXT_LINK STRING,
    ID_OUTLET STRING,
    ITEM_POSITION STRING,
    ITEM_CATEGORY STRING,
    ID_DRINK STRING,
    ITEM_MANUFACTURER STRING,
    ITEM_BRAND STRING,
    ITEM_SUBBRAND STRING,
    ITEM_VOLUME STRING,
    ITEM_PRICE STRING,
    ID_CATEGORY STRING,
    ITEM_DRINK_CATEGORY_1 STRING,
    ITEM_DRINK_CATEGORY_2 STRING,
    ITEM_IMAGE_URL STRING,
    ITEM_IMAGE_HASH STRING,
    ITEM_NAME STRING,
    ITEM_DESC STRING,
    ADDON_PROMPT STRING,
    ADDON_PROMPT_TEXT STRING,
    PACKAGING_SIZE STRING,
    BANNER_AVAILABLE STRING,
    BANNER_IMG_LINK STRING,
    BANNER_IMG_HASH STRING,
    CREATED_AT STRING
);

/* CREATE RAW TABLES INGESTION SNOWPIPES */
CREATE OR REPLACE PIPE REDBULL_DATA.BRONZE.MATCHING_PIPE
AUTO_INGEST = TRUE
AS
COPY INTO REDBULL_DATA.BRONZE.MATCHING_RAW (MARKET, SOURCE_FILE, FILE_ROW_NUMBER, LOAD_TIMESTAMP, RAW_DATA)
FROM (
  SELECT 
    SPLIT_PART(METADATA$FILENAME, '/', 2), 
    METADATA$FILENAME,                     
    METADATA$FILE_ROW_NUMBER,              
    CURRENT_TIMESTAMP(),
    TO_VARCHAR($1)
  FROM @REDBULL_DATA.BRONZE.RAW_STAGE/MATCHING/
)
FILE_FORMAT = (FORMAT_NAME = 'RAW_FORMAT')
ON_ERROR = SKIP_FILE;

CREATE OR REPLACE PIPE REDBULL_DATA.BRONZE.OUTLET_PIPE
AUTO_INGEST = TRUE
AS
COPY INTO REDBULL_DATA.BRONZE.OUTLET_RAW (MARKET, SOURCE_FILE, FILE_ROW_NUMBER, LOAD_TIMESTAMP, RAW_DATA)
FROM (
  SELECT 
    SPLIT_PART(METADATA$FILENAME, '/', 2), 
    METADATA$FILENAME,                     
    METADATA$FILE_ROW_NUMBER,              
    CURRENT_TIMESTAMP(),
    TO_VARCHAR($1)
  FROM @REDBULL_DATA.BRONZE.RAW_STAGE/OUTLET/
)
FILE_FORMAT = (FORMAT_NAME = 'RAW_FORMAT')
ON_ERROR = SKIP_FILE;

CREATE OR REPLACE PIPE REDBULL_DATA.BRONZE.PORTFOLIO_PIPE
AUTO_INGEST = TRUE
AS
COPY INTO REDBULL_DATA.BRONZE.PORTFOLIO_RAW (MARKET, SOURCE_FILE, FILE_ROW_NUMBER, LOAD_TIMESTAMP, RAW_DATA)
FROM (
  SELECT 
    SPLIT_PART(METADATA$FILENAME, '/', 2), 
    METADATA$FILENAME,                     
    METADATA$FILE_ROW_NUMBER,              
    CURRENT_TIMESTAMP(),
    TO_VARCHAR($1)
  FROM @REDBULL_DATA.BRONZE.RAW_STAGE/PORTFOLIO/
)
FILE_FORMAT = (FORMAT_NAME = 'RAW_FORMAT')
ON_ERROR = SKIP_FILE;

/* CREATE PARSED BRONZE TABLES INGESTION SNOWPIPES */
CREATE OR REPLACE PIPE REDBULL_DATA.BRONZE.MATCHING_PARSED_PIPE
AUTO_INGEST = TRUE
AS
COPY INTO REDBULL_DATA.BRONZE.MATCHING_PARSED (
    MARKET, SOURCE_FILE, FILE_ROW_NUMBER, LOAD_TIMESTAMP,
    ID_OUTLET, ID_PLATFORM, PLATFORM_NAME, ID_EXT_LINK, PLACE_ID,
    SIMILARITY_SCORE_NAME, SIMILARITY_SCORE_ADDRESS, MERGED_CHAIN_NAME,
    IS_CHAIN, NUM_RESTAURANTS, SERVES_DRINKS, SERVES_RED_BULL,
    SUGAR_FREE_AVAILABLE, ORGANICS_AVAILABLE, EDITIONS_AVAILABLE, ED,
    ED_COMP, SD_COKE, SD, LEADING_ID_EXT_LINK, CREATED_AT
)
FROM (
  SELECT
    SPLIT_PART(METADATA$FILENAME, '/', 2),
    METADATA$FILENAME,
    METADATA$FILE_ROW_NUMBER,
    CURRENT_TIMESTAMP(),
    $1, $2, $3, $4, $5,
    $6, $7, $8,
    $9, $10, $11, $12,
    $13, $14, $15, $16,
    $17, $18, $19, $20, $21
  FROM @REDBULL_DATA.BRONZE.RAW_STAGE/MATCHING/
)
FILE_FORMAT = (FORMAT_NAME = 'TSV_FORMAT')
ON_ERROR = CONTINUE;

CREATE OR REPLACE PIPE REDBULL_DATA.BRONZE.OUTLET_PARSED_PIPE
AUTO_INGEST = TRUE
AS
COPY INTO REDBULL_DATA.BRONZE.OUTLET_PARSED (
    MARKET, SOURCE_FILE, FILE_ROW_NUMBER, LOAD_TIMESTAMP,
    ID_EXT_LINK, ID_OUTLET, ID_PLATFORM, PLATFORM_NAME, LINK, NAME,
    ADDRESS_BULK, BUSINESS, BUSINESS_URL, DELIVERY, CATEGORY,
    DESCRIPTION, TELEPHONE, LATITUDE, LONGITUDE, NUM_RATINGS,
    AVERAGE_RATING, AVERAGE_COST, CITY, ICON_URL, LOCAL_ICON_NAME,
    MIN_ORDER_AMOUNT, BANNER_AVAILABLE, BANNER_IMG_LINK, BANNER_IMG_HASH,
    MARKET_FIELD, STREET_ADDRESS, POSTAL_CODE, ADDRESS_LOCALITY,
    ADDRESS_COUNTRY, TELEPHONE_PLATFORM, CUISINE, WEBSITE, GHOST_KITCHEN,
    LOCAL_CURRENCY, CREATED_AT, SEGMENT_TYPE
)
FROM (
  SELECT
    SPLIT_PART(METADATA$FILENAME, '/', 2),
    METADATA$FILENAME,
    METADATA$FILE_ROW_NUMBER,
    CURRENT_TIMESTAMP(),
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11,
    $12, $13, $14, $15, $16,
    $17, $18, $19, $20, $21,
    $22, $23, $24, $25, $26,
    $27, $28, $29, $30, $31,
    $32, $33, $34, $35, $36, $37
  FROM @REDBULL_DATA.BRONZE.RAW_STAGE/OUTLET/
)
FILE_FORMAT = (FORMAT_NAME = 'TSV_FORMAT')
ON_ERROR = CONTINUE;

CREATE OR REPLACE PIPE REDBULL_DATA.BRONZE.PORTFOLIO_PARSED_PIPE
AUTO_INGEST = TRUE
AS
COPY INTO REDBULL_DATA.BRONZE.PORTFOLIO_PARSED (
    MARKET, SOURCE_FILE, FILE_ROW_NUMBER, LOAD_TIMESTAMP,
    ID_BEVERAGE, ID_EXT_LINK, ID_OUTLET, ITEM_POSITION, ITEM_CATEGORY,
    ID_DRINK, ITEM_MANUFACTURER, ITEM_BRAND, ITEM_SUBBRAND, ITEM_VOLUME,
    ITEM_PRICE, ID_CATEGORY, ITEM_DRINK_CATEGORY_1, ITEM_DRINK_CATEGORY_2,
    ITEM_IMAGE_URL, ITEM_IMAGE_HASH, ITEM_NAME, ITEM_DESC, ADDON_PROMPT,
    ADDON_PROMPT_TEXT, PACKAGING_SIZE, BANNER_AVAILABLE, BANNER_IMG_LINK,
    BANNER_IMG_HASH, CREATED_AT
)
FROM (
  SELECT
    SPLIT_PART(METADATA$FILENAME, '/', 2),
    METADATA$FILENAME,
    METADATA$FILE_ROW_NUMBER,
    CURRENT_TIMESTAMP(),
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15,
    $16, $17, $18, $19, $20,
    $21, $22, $23, $24, $25
  FROM @REDBULL_DATA.BRONZE.RAW_STAGE/PORTFOLIO/
)
FILE_FORMAT = (FORMAT_NAME = 'TSV_FORMAT')
ON_ERROR = CONTINUE;
