USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS RB_USA_ANALYST;
CREATE ROLE IF NOT EXISTS RB_GBR_ANALYST;
CREATE ROLE IF NOT EXISTS RB_DEU_ANALYST;
CREATE ROLE IF NOT EXISTS RB_HQ_ANALYST;

CREATE SCHEMA IF NOT EXISTS REDBULL_DATA.SECURITY;

CREATE OR REPLACE TABLE REDBULL_DATA.SECURITY.ROLE_MARKET_ENTITLEMENTS (
    ROLE_NAME STRING,
    MARKET STRING
);

INSERT OVERWRITE INTO REDBULL_DATA.SECURITY.ROLE_MARKET_ENTITLEMENTS (ROLE_NAME, MARKET)
SELECT 'RB_USA_ANALYST', 'USA'
UNION ALL
SELECT 'RB_GBR_ANALYST', 'GBR'
UNION ALL
SELECT 'RB_DEU_ANALYST', 'DEU'
UNION ALL
SELECT 'RB_HQ_ANALYST', 'USA'
UNION ALL
SELECT 'RB_HQ_ANALYST', 'GBR'
UNION ALL
SELECT 'RB_HQ_ANALYST', 'DEU';

CREATE OR REPLACE ROW ACCESS POLICY REDBULL_DATA.SECURITY.MARKET_ACCESS_POLICY
AS (MARKET STRING) RETURNS BOOLEAN ->
    EXISTS (
        SELECT 1
        FROM REDBULL_DATA.SECURITY.ROLE_MARKET_ENTITLEMENTS ent
        WHERE ent.ROLE_NAME = CURRENT_ROLE()
          AND ent.MARKET = MARKET
    )
    OR CURRENT_ROLE() IN ('ACCOUNTADMIN', 'SYSADMIN', 'SECURITYADMIN');

EXECUTE IMMEDIATE $$
BEGIN
    BEGIN
        ALTER VIEW REDBULL_DATA.GOLD.DIM_MARKET DROP ROW ACCESS POLICY REDBULL_DATA.SECURITY.MARKET_ACCESS_POLICY;
    EXCEPTION
        WHEN STATEMENT_ERROR THEN NULL;
    END;
    BEGIN
        ALTER VIEW REDBULL_DATA.GOLD.DIM_PLATFORM DROP ROW ACCESS POLICY REDBULL_DATA.SECURITY.MARKET_ACCESS_POLICY;
    EXCEPTION
        WHEN STATEMENT_ERROR THEN NULL;
    END;
    BEGIN
        ALTER VIEW REDBULL_DATA.GOLD.DIM_OUTLET DROP ROW ACCESS POLICY REDBULL_DATA.SECURITY.MARKET_ACCESS_POLICY;
    EXCEPTION
        WHEN STATEMENT_ERROR THEN NULL;
    END;
    BEGIN
        ALTER VIEW REDBULL_DATA.GOLD.DIM_PRODUCT DROP ROW ACCESS POLICY REDBULL_DATA.SECURITY.MARKET_ACCESS_POLICY;
    EXCEPTION
        WHEN STATEMENT_ERROR THEN NULL;
    END;
    BEGIN
        ALTER VIEW REDBULL_DATA.GOLD.FCT_OUTLET_PRODUCT_LISTING DROP ROW ACCESS POLICY REDBULL_DATA.SECURITY.MARKET_ACCESS_POLICY;
    EXCEPTION
        WHEN STATEMENT_ERROR THEN NULL;
    END;
END;
$$;

ALTER VIEW REDBULL_DATA.GOLD.DIM_MARKET ADD ROW ACCESS POLICY REDBULL_DATA.SECURITY.MARKET_ACCESS_POLICY ON (MARKET);
ALTER VIEW REDBULL_DATA.GOLD.DIM_PLATFORM ADD ROW ACCESS POLICY REDBULL_DATA.SECURITY.MARKET_ACCESS_POLICY ON (MARKET);
ALTER VIEW REDBULL_DATA.GOLD.DIM_OUTLET ADD ROW ACCESS POLICY REDBULL_DATA.SECURITY.MARKET_ACCESS_POLICY ON (MARKET);
ALTER VIEW REDBULL_DATA.GOLD.DIM_PRODUCT ADD ROW ACCESS POLICY REDBULL_DATA.SECURITY.MARKET_ACCESS_POLICY ON (MARKET);
ALTER VIEW REDBULL_DATA.GOLD.FCT_OUTLET_PRODUCT_LISTING ADD ROW ACCESS POLICY REDBULL_DATA.SECURITY.MARKET_ACCESS_POLICY ON (MARKET);

GRANT USAGE ON DATABASE REDBULL_DATA TO ROLE RB_USA_ANALYST;
GRANT USAGE ON DATABASE REDBULL_DATA TO ROLE RB_GBR_ANALYST;
GRANT USAGE ON DATABASE REDBULL_DATA TO ROLE RB_DEU_ANALYST;
GRANT USAGE ON DATABASE REDBULL_DATA TO ROLE RB_HQ_ANALYST;

GRANT USAGE ON SCHEMA REDBULL_DATA.GOLD TO ROLE RB_USA_ANALYST;
GRANT USAGE ON SCHEMA REDBULL_DATA.GOLD TO ROLE RB_GBR_ANALYST;
GRANT USAGE ON SCHEMA REDBULL_DATA.GOLD TO ROLE RB_DEU_ANALYST;
GRANT USAGE ON SCHEMA REDBULL_DATA.GOLD TO ROLE RB_HQ_ANALYST;

GRANT SELECT ON ALL VIEWS IN SCHEMA REDBULL_DATA.GOLD TO ROLE RB_USA_ANALYST;
GRANT SELECT ON ALL VIEWS IN SCHEMA REDBULL_DATA.GOLD TO ROLE RB_GBR_ANALYST;
GRANT SELECT ON ALL VIEWS IN SCHEMA REDBULL_DATA.GOLD TO ROLE RB_DEU_ANALYST;
GRANT SELECT ON ALL VIEWS IN SCHEMA REDBULL_DATA.GOLD TO ROLE RB_HQ_ANALYST;

GRANT SELECT ON FUTURE VIEWS IN SCHEMA REDBULL_DATA.GOLD TO ROLE RB_USA_ANALYST;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA REDBULL_DATA.GOLD TO ROLE RB_GBR_ANALYST;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA REDBULL_DATA.GOLD TO ROLE RB_DEU_ANALYST;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA REDBULL_DATA.GOLD TO ROLE RB_HQ_ANALYST;

GRANT USAGE ON SCHEMA REDBULL_DATA.SECURITY TO ROLE RB_USA_ANALYST;
GRANT USAGE ON SCHEMA REDBULL_DATA.SECURITY TO ROLE RB_GBR_ANALYST;
GRANT USAGE ON SCHEMA REDBULL_DATA.SECURITY TO ROLE RB_DEU_ANALYST;
GRANT USAGE ON SCHEMA REDBULL_DATA.SECURITY TO ROLE RB_HQ_ANALYST;
